# Triggers
on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master
# Functions
jobs:
    # Build Job
    build:
        # Name of the job
        name: Build
        # The OS to run the job on
        runs-on: ubuntu-latest
        # Steps
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2
            - name: Install node
              uses: actions/setup-node@v1
              with:
                  node-version: 18.x
            - name: Install NPM Dependencies
              run: npm install -w client
            - name: Build Project
              run: npm run build -w client
            - name: Upload artifact in order to deploy
              uses: actions/upload-artifact@v2
              with:
                  name: production-files
                  path: ./client/dist
    # Deploy Job
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        needs: build

        steps:
            - name: Download artifact
              uses: actions/download-artifact@v2
              with:
                  name: production-files
                  path: ./client/dist
            - name: Deploy to gh pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GH_ACCESS_TOKEN }}
                  publish_dir: ./client/dist
